#+TITLE: Pemrograman Rust

* Abstrak
Buku ini dibuat sebagai catatan untuk rust. Rust katanya sangat bagus untuk 
system engineer, buat saya yang masih junior dalam System Engineer mempelajari
pemrograman ini menjadi cukup menarik.

* Install Rust 
** Pemasangan Rust pada Linux 
#+BEGIN_SRC bash
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
export PATH="$HOME/.cargo/bin:$PATH"
#+END_SRC
** Update Rust
#+BEGIN_SRC bash
rustup update
#+END_SRC
** Uninstall Rust
#+BEGIN_SRC bash
rustup self uninstall
#+END_SRC

** Check Version
#+BEGIN_SRC bash
rustc --version
#+END_SRC 
** Test Program
#+BEGIN_SRC bash
mkdir 1_Hello_World
cd 1_Hello_World/
#+END_SRC
Buatlah sebuah code untuk untuk melakukan test program dengan nama
#+BEGIN_SRC bash
main.rs
#+END_SRC
Tulis kode berikut
#+BEGIN_SRC rust
fn main() {
println!("Hello, world!");
}
#+END_SRC
Kemudian kompile dengan perintah berikut
#+BEGIN_SRC bash
rustc main.rs
#+END_SRC
jalankan program dengan perintah berikut
#+BEGIN_SRC bash
./main
#+END_SRC

** Cargo
*** Inisiasi Project
Saat kita menginstall rust biasaya akan ada bawaan cargo.

#+BEGIN_SRC bash
cargo new hello_cargo --bin
cd hello_cargo
#+END_SRC
untuk build
#+BEGIN_SRC bash
cargo build
#+END_SRC
setelah menjalakan cargo build, proses ini akan menghasilkan
file. Dengan menjalankan perintah dibawah ini kita akan menjalankan program
#+BEGIN_SRC bash
./target/debug/hello_cargo 
#+END_SRC
alternatif dengan langsung mengakses file binarynya kita bisa menggunakan
perintah dibawah ini untuk langsung menjalanakan programmnya.
#+BEGIN_SRC bash
cargo run
#+END_SRC

* Syntax Dasar
** Output
** Input
** Conditional
** Iterasi
